# Generated by Django 2.2.4 on 2019-08-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_referencia'),
        ('producto', '0003_auto_20190828_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comun.Referencia'),
        ),
    ]
