# Generated by Django 2.2.4 on 2019-10-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_visible',
            field=models.BooleanField(default=True, verbose_name='cantidad visible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_visible',
            field=models.BooleanField(default=True, verbose_name='descripcion visible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=12, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_visible',
            field=models.BooleanField(default=True, verbose_name='precio visible'),
        ),
    ]
