# Generated by Django 2.2.4 on 2019-08-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '__first__'),
        ('comun', '__first__'),
        ('trabajador', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_vale', models.IntegerField(blank=True, null=True, verbose_name='No de venta')),
                ('fecha', models.DateField(verbose_name='Fecha emision')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comun.Tipopago')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'vale',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Vale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canti', models.FloatField(default=0, verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('subtotal', models.FloatField(blank=True, editable=False, null=True, verbose_name='Subtotal')),
                ('id_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('id_vale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.Vale')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalle de ventas',
                'db_table': 'detalle_vale',
            },
        ),
    ]
