# Generated by Django 2.2.4 on 2019-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20191003_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='canti',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad'),
        ),
    ]
