# Generated by Django 2.2.4 on 2019-10-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20191003_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='canti',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
    ]
