# Generated by Django 2.2.4 on 2019-10-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20191003_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='canti',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
