# Generated by Django 2.2.4 on 2019-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20191003_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='canti',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
    ]
