# Generated by Django 2.2.4 on 2019-10-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
