# Generated by Django 2.2.4 on 2019-08-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajador', '0001_initial'),
        ('producto', '0002_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ingreso', models.IntegerField(blank=True, null=True, verbose_name='No de ingreso')),
                ('fecha', models.DateField(verbose_name='Fecha emision')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador')),
            ],
            options={
                'verbose_name': 'Ingreso de mercaderia',
                'verbose_name_plural': 'Ingresos de mercaderia',
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canti', models.FloatField(default=0, verbose_name='Cantidad')),
                ('id_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ingreso.Ingreso')),
                ('id_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
            options={
                'verbose_name': 'Detalle de ingreso de mercaderia',
                'verbose_name_plural': 'Detalle de ingresos de mercaderia',
                'db_table': 'detalle_ingreso',
            },
        ),
    ]
