# Generated by Django 2.2.4 on 2019-09-08 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 21, 52, 21, 832492), verbose_name='Fecha emision'),
        ),
    ]
