# Generated by Django 2.2.4 on 2019-10-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0004_auto_20191003_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='no_ingreso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No de ingreso'),
        ),
    ]
