# Generated by Django 2.2.4 on 2019-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0005_auto_20191003_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='canti',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='no_ingreso',
            field=models.IntegerField(blank=True, null=True, verbose_name='No de ingreso'),
        ),
    ]
